services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres-auth:
    image: postgres:16
    container_name: postgres-auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
  postgres-orders:
    image: postgres:16
    container_name: postgres-orders
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    ports:
      - "5433:5432"
    volumes:
      - postgres_orders_data:/var/lib/postgresql/data
  postgres-payment:
    image: postgres:16
    container_name: postgres-payment
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment
    ports:
      - "5434:5432"
    volumes:
      - postgres_payment_data:/var/lib/postgresql/data
  postgres-products:
    image: postgres:16
    container_name: postgres-products
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
    ports:
      - "5435:5432"
    volumes:
      - postgres_products_data:/var/lib/postgresql/data
  postgres-stock:
    image: postgres:16
    container_name: postgres-stock
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stock
    ports:
      - "5436:5432"
    volumes:
      - postgres_stock_data:/var/lib/postgresql/data 

volumes:
  postgres_auth_data:
  postgres_orders_data:
  postgres_payment_data:
  postgres_products_data:
  postgres_stock_data: